export let projects = [
  {
    id: 1,
    name: "Portfolio",
    desc: "A modern portfolio website with Next.js and Tailwind CSS.",
    responsive: "responsive",
    time: "2022/10/01",
    banner: "/p1.png",
    techs: ["Next.js", "Tailwind CSS"],
    images: ["/p1.png", "/p2.png", "/p3.png"],
    github: "https://github.com/sohail-ahmed/portfolio",
    live: "https://rayan-portfolio.onrender.com/",
  },
  {
    id: 2,
    name: "Mg Company",
    desc: "Company website with Next.js and Tailwind CSS.",
    responsive: "responsive",
    time: "2023/3/9",
    banner: "/m1.png",
    techs: ["Next.js", "Tailwind CSS"],
    images: ["/m1.png", "/m2.png", "/m3.png"],
    github: "https://github.com/sohail-ahmed/portfolio",
    live: "https://final-mg-sys.onrender.com/",
  },
  {
    id: 3,
    name: "Portfolio",
    desc: "social media website with Next.js and Tailwind CSS.",
    responsive: "responsive",
    time: "2024/25/7",
    banner: "/s1.png",
    techs: ["Next.js", "Tailwind CSS"],
    images: ["/s1.png", "/s2.png", "/s3.png"],
    github: "https://github.com/sohail-ahmed/portfolio",
    live: "https://socialmedia36.netlify.app/",
  },
];
